backend skeleton #1
CppRemoteLearning/RTopServer pull request #1
Opened 2023-07-18 11:37 UTC by Lys4nder

2023-07-19 07:14 UTC, CristianIonutIonescu requested changes
generated sources and headers from proto files should not be in include folder but in a subfolder, generated, in build. We don't need to upload the output of proto into git.

2023-07-19 07:14 UTC, CristianIonutIonescu commented on CMakeLists.txt
> +gtest_discover_tests(tests)
I would have this split into a separate cmakefile, under tests folder. Have a look at the scheleton for client

2023-07-19 08:09 UTC, enachebogdan approved these changes
I know this is just a demo of protobuf/grpc, but "person" logic and tests are not relevant for our app. You could either replace it with something related to our app or remove it from the skeleton entirely.

2023-07-19 08:09 UTC, enachebogdan commented on proto/person.proto
> +package person;
you should remove(or replace with something relevant to our app) this as well.

2023-07-19 08:09 UTC, enachebogdan commented on src/main.cc
> +#include "../build/proto_generated/person.pb.h"
all references to "person"must be removed. Your main will not compile with current code.

2023-07-24 07:50 UTC, CristianIonutIonescu approved these changes

2023-07-24 07:52 UTC, merged