Implementation of GatewayConnection
CppRemoteLearning/RTopServer pull request #2
Opened 2023-07-25 10:05 UTC by Lys4nder

To Do:
- [ ]  Write Gtests
- [ ] Write Gmock Tests

2023-07-26 07:29 UTC, CristianIonutIonescu commented on tests/GatewayConnectionTests.h
> +using ::testing::Return;
why do we need these here?

2023-07-26 09:37 UTC, CristianIonutIonescu requested changes
there's still work to do

2023-07-26 09:37 UTC, CristianIonutIonescu commented on src/GatewayConnection.cpp
> +    int bytesSent = send(socket_, msg, strlen(msg), 0);
why do you need an extra variable? can't message.c_str() be used in the send method?

2023-07-26 09:37 UTC, CristianIonutIonescu commented on include/GatewayConnection.h
> +        ~GatewayConnection();
destructor before GetData()

2023-07-26 09:37 UTC, CristianIonutIonescu commented on include/GatewayConnection.h
> +class GatewayConnection {
what about rule of five/zero? Is this class copiable?

2023-07-26 09:37 UTC, CristianIonutIonescu commented on include/GatewayConnection.h
> +        int32_t port_;
are these used outside of constructor?

2023-07-26 09:37 UTC, CristianIonutIonescu commented on include/GatewayConnection.h
> +        struct sockaddr_in server_address_;
do you use this outside of constructor?

2023-07-26 09:37 UTC, CristianIonutIonescu commented on src/main.cc
>      std::cout << p.name() << std::endl;
do you still need this?

2023-07-26 13:42 UTC, marisvali requested changes

2023-07-26 13:42 UTC, marisvali commented on src/GatewayConnection.cpp
> +    int bytesSent = send(socket_, message.c_str(), strlen(message.c_str()), 0);
Use message.length() or message.size(), they are O(1) operations. strlen(message.c_str()) is O(n).

2023-07-26 13:42 UTC, marisvali commented on src/GatewayConnection.cpp
> +    if (close(socket_) == -1) {
You should also do shutdown() before close().

2023-07-26 13:42 UTC, marisvali commented on src/GatewayConnection.cpp
> +    socket_ = std::move(other.socket_);
std::move on an integer has no effect, you're not moving anything, just making a copy. std::move should be removed. But now the question is, is it ok to make a copy? Why yes/no?

2023-07-26 13:42 UTC, marisvali commented on src/GatewayConnection.cpp
> +    socket_ = std::move(other.socket_);
std::move on an integer has no effect, you're not moving anything, just making a copy. std::move should be removed. But now the question is, is it ok to make a copy? Why yes/no?

2023-07-26 14:17 UTC, enachebogdan commented on tests/GatewayConnectionTests.h
I've noticed you only test copy/move semantics, nothing relevant to the GatewayConnection functionality. You should find a way to test all of your functions.

2023-07-26 14:17 UTC, enachebogdan commented on tests/GatewayConnectionTests.h
> +// Before running tests, make sure to start server: nc -l 127.0.0.1 8080
Usually with unit tests we aim for an automatic execution, with no manual steps (starting this server). You should just use mock data to test the functionality.

If you need to use this server for your manual tests that's perfectly fine, it just shouldn't be in the unit test process.

2023-07-28 07:56 UTC, CristianIonutIonescu commented on include/gateway_connection.h
> +        GatewayConnection& operator=(GatewayConnection&& other);                // move assignment operator
doesn't respect google style guide regarding comments

2023-07-28 07:59 UTC, CristianIonutIonescu commented on tests/proto_tests.cpp
> +TEST(MemoryUsageTests, Test)
why do you name all your tests here? read what the parameters of TEST mean

2023-07-28 08:36 UTC, Lys4nder commented on tests/proto_tests.cpp
> +TEST(MemoryUsageTests, Test)
this is not my code, this is from pull origin master

2023-07-28 11:45 UTC, CristianIonutIonescu requested changes
still missing google coding guidelines regarding class and method comments

2023-08-02 14:25 UTC, CristianIonutIonescu reviewed
last issue I saw

2023-08-02 14:25 UTC, CristianIonutIonescu commented on include/gateway_connection.h
> +        GatewayConnection(std::string ip, int32_t port);
I thought we agreed that the port should be an uint16_t, or I discussed in another PR?

2023-08-02 14:45 UTC, CristianIonutIonescu approved these changes

2023-08-02 14:45 UTC, merged