Config for RTopGateway
CppRemoteLearning/RTopServer pull request #6
Opened 2023-07-31 13:32 UTC by Lys4nder

2023-08-01 06:20 UTC, oprisor-adrian commented on RTopGateway/include/config_importer.h
> +namespace ConfigImporter {
I think the namespace should be the same as the RTopGateway service. The _ConfigImporter_ is part of his implementation.

2023-08-01 06:29 UTC, oprisor-adrian commented on RTopGateway/include/config_importer.h
> +            int16_t port_;
The port number can take values up to 65535. Consider using a more appropriate data type.
Port (computer networking): https://en.wikipedia.org/wiki/Port_(computer_networking)

2023-08-01 10:30 UTC, oprisor-adrian commented on RTopGateway/include/config_importer.h
> +    class ConfigImporter {
Try to add comments at your class. Also, you can write an example of how I can use the class.
Style guide: https://google.github.io/styleguide/cppguide.html#Class_Comments

2023-08-01 10:30 UTC, oprisor-adrian commented on RTopGateway/include/config_importer.h
> +            uint16_t port_;
Take a look at function comments and variable comments:
- https://google.github.io/styleguide/cppguide.html#Function_Comments
- https://google.github.io/styleguide/cppguide.html#Variable_Comments

2023-08-01 10:57 UTC, Lys4nder commented on RTopGateway/include/config_importer.h
> +            uint16_t port_;
As per Google's Style guide "Declaration comments describe use of the function **(when it is non-obvious)**" and "In general the actual name of the **variable should be descriptive enough to give a good idea of what the variable is used for.**", therefore, I genuinely don't think there's a need of comments for such a small class.

2023-08-01 10:59 UTC, Lys4nder commented on RTopGateway/include/config_importer.h
> +    class ConfigImporter {
As per Google's Style Guide: "Every **non-obvious** class or struct declaration **should** have an accompanying comment that describes what it is for and how it should be used."

2023-08-02 14:27 UTC, CristianIonutIonescu reviewed
Although the implementation is good and straightforward, I would suggest to look over Singleton pattern and use it for ConfigImporter. It might be overkill at this point but it's a good exercise to do it.
PS: pay attention to singleton pattern in multithreaded environment

2023-08-03 14:08 UTC, CristianIonutIonescu requested changes
Singleton pattern not correctly implemented

2023-08-03 14:08 UTC, CristianIonutIonescu commented on RTopGateway/include/config_importer.h
> +            }
this isn't how a singleton pattern works. read more about it and come with a proper solution

2023-08-09 14:46 UTC, merged