RTopServerImpl
CppRemoteLearning/RTopServer pull request #8
Opened 2023-08-01 13:53 UTC by radavid2017

Features:
- [x] Exceptions Handling
- [x] Google Tests

2023-08-03 13:01 UTC, CristianIonutIonescu reviewed
Apart from what we discussed + comments I've put here, don't forget about google style comments (for classes and methods) also the naming convention of the files

2023-08-03 13:44 UTC, radavid2017 commented on include/rTopServerImpl.h
> +        int32_t port_;
Ok, I read again and I noticed that unsigned int with 16 bits has this range. So it would be cool to use uint16_t I guess

2023-08-03 13:55 UTC, CristianIonutIonescu commented on CMakeLists.txt
> +set(
no, it's not, it's best practice not do add things that are not needed.

2023-08-07 11:28 UTC, CristianIonutIonescu requested changes
Please clarify the grpc:Status exception handling. I'm not expecting grpc to throw statuses as exceptions

2023-08-07 11:28 UTC, CristianIonutIonescu commented on include/rtop_server_exception.h
> +    class RTopServerException : public std::exception {
why not inherit from std::runtime_error https://en.cppreference.com/w/cpp/error/runtime_error? It will be a specialisation of it but without the overhead of needing to take care of what and message

2023-08-07 11:28 UTC, CristianIonutIonescu commented on src/rtop_server_impl.cpp
> +        } catch (grpc::Status status) {
is grpc::Status thrown as an exception?

2023-08-08 12:39 UTC, radavid2017 commented on src/rtop_server_impl.cpp
> +        } catch (grpc::Status status) {
I think it's debatable. Found a source with error handling in grpc c++:

https://github.com/grpc/grpc/tree/master/examples/cpp/error_handling

Here, the server-side throw errors as status codes. In the server app the status is declared in method which gets a request and the status gets OK if everything worked fine, or it will get another status depending on the error.
Also, in this example, the server throws the status (as an exception/error) and the client is handling it.

2023-08-09 15:02 UTC, enachebogdan commented on src/rtop_server_impl.cpp
> +            std::cout << "RTopServer: status code:\n";
Maybe I'm missing it, but do you actually print the actual status code anywhere after this message?

2023-08-10 08:43 UTC, radavid2017 commented on src/rtop_server_impl.cpp
> +            std::cout << "RTopServer: status code:\n";
I found will put the duplicate code into the status printer. I missed the actual printing of the status info, so I will fix it. Thank you for your help!

2023-08-10 08:46 UTC, radavid2017 commented on src/rtop_server_impl.cpp
> +            case grpc::CANCELLED: return grpc::Status(status.error_code(), "Operation cancelled: " + status.error_message());
Thank you for advise and for the "shadowed" warning. I found here 

https://stackoverflow.com/questions/7822967/do-i-need-a-break-after-return-in-my-function

that using break after return is a dead code. I will fix this out!

2023-08-11 07:38 UTC, enachebogdan submitted a review, later dismissed

2023-08-11 08:03 UTC, CristianIonutIonescu submitted a review, later dismissed

2023-08-11 11:39 UTC, CristianIonutIonescu approved these changes

2023-08-11 11:40 UTC, merged